import os
import re
import sqlite3
from pathlib import Path


def _is_postgres_url(value):
    value = str(value or "").strip().lower()
    return value.startswith("postgres://") or value.startswith("postgresql://")


def _replace_sqlite_placeholders(sql):
    result = []
    in_single = False
    in_double = False
    escape = False

    for ch in str(sql):
        if escape:
            result.append(ch)
            escape = False
            continue

        if ch == "\\":
            result.append(ch)
            escape = True
            continue

        if ch == "'" and not in_double:
            in_single = not in_single
            result.append(ch)
            continue

        if ch == '"' and not in_single:
            in_double = not in_double
            result.append(ch)
            continue

        if ch == "?" and not in_single and not in_double:
            result.append("%s")
        else:
            result.append(ch)

    return "".join(result)



def _escape_percent_for_psycopg(sql):
    sql = str(sql or "")
    result = []
    i = 0

    while i < len(sql):
        ch = sql[i]
        nxt = sql[i + 1] if i + 1 < len(sql) else ""

        if ch == "%":
            if nxt in {"s", "b", "t"}:
                result.append("%" + nxt)
                i += 2
                continue
            if nxt == "%":
                result.append("%%")
                i += 2
                continue
            result.append("%%")
            i += 1
            continue

        result.append(ch)
        i += 1

    return "".join(result)


def _adapt_sql_for_postgres(sql):
    sql = str(sql or "").strip()

    sql = re.sub(
        r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
        sql,
        flags=re.IGNORECASE,
    )

    sql = re.sub(
        r"datetime\(([^)]+)\)",
        r"\1",
        sql,
        flags=re.IGNORECASE,
    )

    sql = _replace_sqlite_placeholders(sql)

    sql = sql.replace(
        "max(0, min(100, trust_score + %s))",
        "GREATEST(0, LEAST(100, trust_score + %s))",
    )

    sql = _escape_percent_for_psycopg(sql)

    return sql


def _split_sql_script(script):
    statements = []
    current = []
    in_single = False
    in_double = False
    escape = False

    for ch in str(script or ""):
        if escape:
            current.append(ch)
            escape = False
            continue

        if ch == "\\":
            current.append(ch)
            escape = True
            continue

        if ch == "'" and not in_double:
            in_single = not in_single
            current.append(ch)
            continue

        if ch == '"' and not in_single:
            in_double = not in_double
            current.append(ch)
            continue

        if ch == ";" and not in_single and not in_double:
            statement = "".join(current).strip()
            if statement:
                statements.append(statement)
            current = []
        else:
            current.append(ch)

    tail = "".join(current).strip()
    if tail:
        statements.append(tail)

    return statements


class StaticResult:
    def __init__(self, rows=None, lastrowid=None):
        self._rows = list(rows or [])
        self._index = 0
        self.lastrowid = lastrowid

    def fetchone(self):
        if self._index >= len(self._rows):
            return None
        row = self._rows[self._index]
        self._index += 1
        return row

    def fetchall(self):
        if self._index >= len(self._rows):
            return []
        rows = self._rows[self._index:]
        self._index = len(self._rows)
        return rows


class CursorResult:
    def __init__(self, cursor, lastrowid=None):
        self._cursor = cursor
        self.lastrowid = lastrowid

    def fetchone(self):
        row = self._cursor.fetchone()
        return row

    def fetchall(self):
        return self._cursor.fetchall()


class PostgresConnection:
    def __init__(self, database_url):
        try:
            import psycopg
            from psycopg.rows import dict_row
        except Exception as exc:
            raise RuntimeError(
                "PostgreSQL mode requires psycopg. Install requirements.txt first."
            ) from exc

        self._psycopg = psycopg
        self._conn = psycopg.connect(
            database_url,
            row_factory=dict_row,
            connect_timeout=int(os.environ.get("PGCONNECT_TIMEOUT", "8")),
        )
        self._last_insert_id = None

    def execute(self, sql, params=None):
        raw_sql = str(sql or "").strip()

        pragma_match = re.match(r"PRAGMA\s+table_info\(([^)]+)\)", raw_sql, re.IGNORECASE)
        if pragma_match:
            table_name = pragma_match.group(1).strip().strip('"').strip("'")
            cur = self._conn.cursor()
            cur.execute(
                """
                SELECT column_name AS name
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = %s
                ORDER BY ordinal_position
                """,
                (table_name,),
            )
            return StaticResult(cur.fetchall())

        if re.search(r"SELECT\s+last_insert_rowid\(\)\s+AS\s+id", raw_sql, re.IGNORECASE):
            return StaticResult([{"id": self._last_insert_id}])

        sql_to_run = _adapt_sql_for_postgres(raw_sql)
        params = tuple(params or ())

        insert_match = re.match(r"INSERT\s+INTO\s+([A-Za-z_][A-Za-z0-9_]*)\b", sql_to_run, re.IGNORECASE)
        is_insert = bool(insert_match)
        has_returning = bool(re.search(r"\bRETURNING\b", sql_to_run, re.IGNORECASE))

        cur = self._conn.cursor()

        try:
            if is_insert and not has_returning:
                sql_with_returning = sql_to_run + " RETURNING id"
                try:
                    cur.execute(sql_with_returning, params)
                    row = cur.fetchone()
                    self._last_insert_id = row["id"] if row and "id" in row else None
                    return StaticResult([], lastrowid=self._last_insert_id)
                except Exception:
                    self._conn.rollback()
                    cur = self._conn.cursor()
                    cur.execute(sql_to_run, params)
                    self._last_insert_id = None
                    return CursorResult(cur, lastrowid=None)

            cur.execute(sql_to_run, params)
            return CursorResult(cur, lastrowid=self._last_insert_id)
        except Exception:
            raise

    def executescript(self, script):
        for statement in _split_sql_script(script):
            if statement.strip().upper().startswith("PRAGMA "):
                continue
            self.execute(statement)
        return None

    def commit(self):
        return self._conn.commit()

    def rollback(self):
        return self._conn.rollback()

    def close(self):
        return self._conn.close()


def connect_database(db_path, database_url=""):
    if _is_postgres_url(database_url):
        return PostgresConnection(database_url)

    db_path = Path(db_path)
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn
